server:
  port: 12801
spring:
  datasource:
    url: jdbc:mysql:///mobile_gateway?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mobile:
  gateway:
    httpclient:
      strategy: webclient
    sync:
      websocket:
        enabled: true
        messageMaxSize: 10240
        allowOrigins: ws://localhost:12800
#      zookeeper:
#        url: localhost:2181
#        sessionTimeout: 5000
#        connectionTimeout: 2000
#      http:
#        enabled: true
#      nacos:
#        url: localhost:8848
#        namespace: 1c10d748-af86-43b9-8265-75f487d20c6c
#        username:
#        password:
#        acm:
#          enabled: false
#          endpoint: acm.aliyun.com
#          namespace:
#          accessKey:
#          secretKey:
#      etcd:
#        url: http://localhost:2379
#      consul:
#        url: http://localhost:8500